# Generated by Django 4.2.4 on 2023-08-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='self_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_profile', to='API.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_profile', to='API.profile'),
        ),
    ]
