# Generated by Django 4.2.4 on 2023-08-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_friend_self_profile_alter_friend_friend_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_profiles', to='API.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='self_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_profiles', to='API.profile'),
        ),
    ]
