# Generated by Django 4.2.4 on 2023-08-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_dms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMs',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.chat')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='FriendDMs1', to='API.friend')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='FriendDMs2', to='API.friend')),
            ],
            bases=('API.chat',),
        ),
    ]
