# Generated by Django 4.2.4 on 2023-08-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_dms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DMs',
        ),
    ]
