# Generated by Django 4.2.4 on 2023-08-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_delete_dms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bungo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
