# Generated by Django 4.2.4 on 2023-08-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_bungo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bungo',
        ),
    ]
