# Generated by Django 4.2.4 on 2023-08-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_bungo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bungo',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
