# Generated by Django 4.2.4 on 2023-08-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_delete_bungo_remove_message_chat_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='DM', max_length=32)),
                ('chat_name', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
