# Generated by Django 4.2.4 on 2023-08-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_chat_members_alter_friend_friend_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='API.chat'),
        ),
    ]
